set_day_kwh:
  name: Установить дневные показания
  description: Установить значение дневного счетчика (кВт·ч)
  target:
    entity:
      integration: pulse_counter
  fields:
    value:
      name: Значение
      description: Новое значение в кВт·ч
      required: true
      selector:
        number:
          min: 0
          step: 0.01
          unit_of_measurement: "кВт·ч"

set_night_kwh:
  name: Установить ночные показания
  description: Установить значение ночного счетчика (кВт·ч)
  target:
    entity:
      integration: pulse_counter
  fields:
    value:
      name: Значение
      description: Новое значение в кВт·ч
      required: true
      selector:
        number:
          min: 0
          step: 0.01
          unit_of_measurement: "кВт·ч"

set_total_value:
  name: Установить показания
  description: Установить значение счетчика
  target:
    entity:
      integration: pulse_counter
  fields:
    value:
      name: Значение
      description: Новое значение
      required: true
      selector:
        number:
          min: 0
          step: 0.01

reset_monthly:
  name: Сбросить месячные показания
  description: Принудительный сброс счетчиков за месяц
  target:
    entity:
      integration: pulse_counter


test_notification:
  name: Тестовое уведомление
  description: Отправить тестовое уведомление с текущими показаниями счетчика
  target:
    entity:
      integration: pulse_counter
  fields:
    service:
      name: Сервис уведомлений
      description: Куда отправить тестовое уведомление
      required: false
      default: "persistent_notification"
      selector:
        text:
